version: "3.7"

services:
  auth:
    container_name: flies_auth
    image: flies-auth
    restart: always
    env_file:
      - ../.env
    ports:
      - 8180:8080
    depends_on:
      - db
  db:
    container_name: flies_postgres
    image: postgres
    restart: always
    hostname: postgresdb
    environment:
      POSTGRES_USER: flies_auth
      POSTGRES_PASSWORD: fl13s_Auth
      POSTGRES_DB: flies_auth
    ports:
      - 5432:5432
    volumes:
      - flies_postgres:/var/lib/postgresql/data

volumes:
  flies_postgres:
