version: '3.3'

services:
  auth:
    image: flies-auth
    restart: always
    environment:
      FA_PORT: 8088
      FA_DATABASE_URL: postgres://flies_auth:fl13s_Auth@db:5432/flies_auth
      # GMAIL_USERNAME: gaconkzk@gmail.com
      # GMAIL_PASSWORD: QW3rT(1234)
    ports:
      - 127.0.0.1:8088:8088
  db:
    image: postgres
    restart: always
    hostname: postgresdb
    environment:
      POSTGRES_USER: flies_auth
      POSTGRES_PASSWORD: fl13s_Auth
      POSTGRES_DB: flies_auth
    ports:
      - 5432:5432
    volumes:
      - flies_postgres:/var/lib/postgresql/data

volumes:
  flies_postgres:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "10.10.11.1/22"
